"""change permissions.permission to permissions.text

Revision ID: e5f47bd45ff6
Revises: e8e458d8fe58
Create Date: 2019-05-27 04:26:30.725812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f47bd45ff6'
down_revision = 'e8e458d8fe58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('text', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'permissions', ['text'])
    op.drop_column('permissions', 'permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('permission', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'permissions', type_='unique')
    op.drop_column('permissions', 'text')
    # ### end Alembic commands ###
